set number

imap éé <Esc>
vmap éé <Esc>
omap éé <Esc>

filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab

autocmd FileType python map <buffer> <F5> :w<CR>:exec '!py' shellescape(@%, 1)<CR>
autocmd FileType python imap <buffer> <F5> <esc>:w<CR>:exec '!py' shellescape(@%, 1)<CR>

map <F5> :w<CR> :!clear; make<CR> :!./build/main<CR>

set clipboard=unnamedplus
